import { writeFileSync } from "node:fs";
import { loadBank, QUESTION_FILES } from "../server/bank.js";
import { MODES } from "../shared/schema.js";
const bank = loadBank();
console.log(
  `Valid question bank: ${bank.length} records (${MODES.map((m) => `${m}: ${bank.filter((q) => q.mode === m).length}`).join(", ")}).`,
);
if (process.argv.includes("--catalog")) {
  const text =
    "# Question catalog\n\nGenerated by `npm run catalog`. Edit the JSON files, not this catalog.\n\n" +
    MODES.map(
      (mode, i) =>
        `## ${QUESTION_FILES[i]}\n\n` +
        bank
          .filter((q) => q.mode === mode)
          .map(
            (q, n) =>
              `${n + 1}. **${q.id}** · ${q.pack} — ${q.text}${q.options ? ` (${q.options.map((o) => `${o.id}: ${o.text}`).join(" / ")})` : ""}`,
          )
          .join("\n"),
    ).join("\n\n") +
    "\n";
  writeFileSync("questions/CATALOG.md", text);
}
